name: Dogs Service CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Dependencies
      run: yarn
      
    - name: Create .env file
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
      run: |
        touch .env
        echo DATABASE_URL=$DATABASE_URL >> .env
        echo SHADOW_DATABASE_URL=$SHADOW_DATABASE_URL >> .env

    - name: Run test
      run: yarn test

    - name: Check ESLint
      run: yarn lint
      
    - name: Remove .env file
    - run: rm .env
