name: Dogs Service CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Create .env file
      run: |
        touch .env
        echo DATABASE_URL=${{ env.DATABASE_URL }} >> .env
        echo SHADOW_DATABASE_URL=${{ env.SHADOW_DATABASE_URL }} >> .env

    - name: Install Dependencies
      run: yarn

    - name: Run test
      run: yarn test

    - name: Check ESLint
      run: yarn lint
